### ISSUE TITLE
Add option to move tex files to documents folder.

### ISSUE THREAD

**Issue by danishprakash** [prakashdanish/yafo#1]
Add an option to move `.tex` files, automatically to the `Documents` folder.

**Comment by AdeilH** [comment]
Hey I would like to take this. I am just starting.

**Comment by danishprakash** [comment]
**NOTE**: Please don't work on this issue, there are already 4 PRs for this issue and I'm unable to assign assignees to this project due to some issue and that just adds to the problem, please look for other issues.
Good Luck!
